Description: A simple ASG + LaunchTemplate
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  InstanceTypeParameter1:
    Type: String
    Default: t3.nano
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
  InstanceTypeParameter2:
    Type: String
    Default: t3.nano
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
  MinSizeParameter:
    Type: Number
  MaxSizeParameter:
    Type: Number
  DesiredCapacityParameter:
    Type: Number
  OnDemandBaseCapacityParameter:
    Type: Number
  OnDemandPercentageAboveBaseCapacityParameter:
    Type: Number

Resources:

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: KyuminSpotTemplate
      LaunchTemplateData:
        ImageId: ami-06ba88d1be185b5c2
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: LaunchTemplate
    Properties:
      MinSize: !Ref MinSizeParameter
      MaxSize: !Ref MaxSizeParameter
      DesiredCapacity: !Ref DesiredCapacityParameter
      VPCZoneIdentifier:
        - subnet-2ae2da42
        - subnet-80d108cc
        - subnet-bfe89ec5
      MixedInstancesPolicy:
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateName: KyuminSpotTemplate
            Version: '1'
          Overrides:
            - InstanceType: !Ref InstanceTypeParameter1
            - InstanceType: !Ref InstanceTypeParameter2
        InstancesDistribution:
          OnDemandBaseCapacity: !Ref OnDemandBaseCapacityParameter
          OnDemandPercentageAboveBaseCapacity: !Ref OnDemandPercentageAboveBaseCapacityParameter




